version: '2'
services:
  hdfsyarn:
     image:  skymindio-docker-dl4j-hadoop.bintray.io/skymindio/dl4j-hadoop
     entrypoint: /opt/runbootstrap.sh
     ports:
      - "50010:50010"
      - "50020:50020"
      - "50070:50070"
      - "50075:50075"
      - "50090:50090"
      - "8020:8020"
      - "9000:9000"
      - "10020:10020"
      - "19888:19888"
      - "8030:8030"
      - "8031:8031"
      - "8033:8033"
      - "8040:8040"
      - "8042:8042"
      - "8088:8088"
      - "49707:49707"

  hdfsslavenode:
       image:  skymindio-docker-dl4j-hadoop.bintray.io/skymindio/dl4j-hadoop
       entrypoint: /opt/runbootstrap.sh
       depends_on:
         - hdfsyarn


  spark-master:
      image: skymindio-docker-dl4j-spark.bintray.io/skymindio/dl4j-spark
      entrypoint: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      environment:
         SPARK_MASTER_WEBUI_PORT: 8280
         MKL_THREADING_LAYER: "GNU"
         LD_PRELOAD: "/usr/lib64/libgomp.so.1"
         JAVA_HOME: /opt/jdk1.8.0_91/
      ports:
         - "7070:7070"
         - "8280:8280"
      volumes:
        - "./workspace:/workspace"

  spark-slave:
        ports:
          - "8081:8081"
        image: skymind/spark
        environment:
             MKL_THREADING_LAYER: "GNU"
             LD_PRELOAD: "/usr/lib64/libgomp.so.1"

        volumes:
           - "./slaves:/opt/spark/conf/slaves"

        entrypoint: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
        depends_on:
           - spark-master


  zookeeper:
       expose:
          - "2180"
       ports:
        - "2180:2180"
        - "2181:2181"
        - "2888:2888"
        - "3888:3888"
       image: jplock/zookeeper:3.4.5

  kafka:
   environment:
      #change this to be the output of: python -c 'import socket;print socket.gethostbyname(socket.gethostname())'
     # KAFKA_ADVERTISED_HOST_NAME: 172.16.1.90
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
     # KAFKA_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "dl4j-predict:1:1,dl4j-serving:1:1,dl4j-eval:1:1"
   volumes:
            - /var/run/docker.sock:/var/run/docker.sock
   ports:
         - "9092:9092"

   image: wurstmeister/kafka:0.8.2.2
   links:
       - zookeeper
   depends_on:
         - zookeeper
         - kibana
         - elasticsearch
